# Generacy Development Cluster Setup
#
# Run this script after cloning/forking to configure the cluster
# for your project. It will:
#   1. Detect your project from the git remote
#   2. Create a smee.io webhook channel
#   3. Generate .env with project settings
#   4. Generate .env.local with your credentials
#   5. Update devcontainer.json with project values
#   6. Ensure ~/.claude.json exists for Docker volume mount
#
# Usage:
#   .\setup.ps1
#   .\setup.ps1 -RepoUrl https://github.com/your-org/your-repo.git

param(
    [string]$RepoUrl = ""
)

$ErrorActionPreference = "Stop"
$DevcontainerDir = Join-Path $PSScriptRoot ".devcontainer"

# -- Helpers ------------------------------------------------------------------

function Write-Info  { Write-Host "==> $args" -ForegroundColor Blue }
function Write-Ok    { Write-Host "  + $args" -ForegroundColor Green }
function Write-Warn  { Write-Host "  ! $args" -ForegroundColor Yellow }
function Write-Err   { Write-Host "  x $args" -ForegroundColor Red }

# -- Step 1: Detect project --------------------------------------------------

Write-Info "Detecting project..."

if (-not $RepoUrl) {
    try { $RepoUrl = git remote get-url origin 2>$null } catch {}
}

if (-not $RepoUrl) {
    $RepoUrl = Read-Host "  ? Repository URL (e.g., https://github.com/your-org/your-repo.git)"
}

if (-not $RepoUrl) {
    Write-Err "Repository URL is required"
    exit 1
}

# Derive names from URL
$RepoName = [System.IO.Path]::GetFileNameWithoutExtension($RepoUrl.TrimEnd('/'))
$ProjectName = ($RepoName.ToLower() -replace '[^a-z0-9-]', '-')

Write-Ok "Repository: $RepoUrl"
Write-Ok "Project name: $ProjectName"
Write-Ok "Repo name: $RepoName"

# -- Step 2: Branch -----------------------------------------------------------

$RepoBranch = try { git symbolic-ref --short HEAD 2>$null } catch { "main" }
if (-not $RepoBranch) { $RepoBranch = "main" }
$input = Read-Host "  ? Default branch [$RepoBranch]"
if ($input) { $RepoBranch = $input }
Write-Ok "Branch: $RepoBranch"

# -- Step 3: Worker count ----------------------------------------------------

$WorkerCount = "3"
$input = Read-Host "  ? Number of workers [$WorkerCount]"
if ($input) { $WorkerCount = $input }
Write-Ok "Workers: $WorkerCount"

# -- Step 4: Create smee.io channel ------------------------------------------

Write-Info "Setting up webhook forwarding..."

$SmeeChannelUrl = ""
$createSmee = Read-Host "  ? Create a new smee.io channel? [Y/n]"
if ($createSmee -ne "n" -and $createSmee -ne "N") {
    try {
        $response = Invoke-WebRequest -Uri "https://smee.io/new" -MaximumRedirection 0 -ErrorAction SilentlyContinue
    } catch {
        if ($_.Exception.Response.Headers.Location) {
            $SmeeChannelUrl = $_.Exception.Response.Headers.Location.ToString()
        }
    }
    if ($SmeeChannelUrl) {
        Write-Ok "Smee channel: $SmeeChannelUrl"
    } else {
        Write-Warn "Could not create smee.io channel automatically"
    }
}

if (-not $SmeeChannelUrl) {
    $SmeeChannelUrl = Read-Host "  ? Smee.io channel URL (create one at https://smee.io/new, or press Enter to skip)"
    if ($SmeeChannelUrl) {
        Write-Ok "Smee channel: $SmeeChannelUrl"
    } else {
        Write-Warn "Skipping smee.io - you can add SMEE_CHANNEL_URL to .env later"
    }
}

# -- Step 5: Generate .env ---------------------------------------------------

Write-Info "Generating .devcontainer/.env..."

$EnvFile = Join-Path $DevcontainerDir ".env"
$writeEnv = $true

if (Test-Path $EnvFile) {
    $overwrite = Read-Host "  ? .env already exists. Overwrite? [y/N]"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Warn "Keeping existing .env"
        $writeEnv = $false
    }
}

if ($writeEnv) {
    $timestamp = (Get-Date).ToUniversalTime().ToString("yyyy-MM-ddTHH:mm:ssZ")
    $envContent = @"
# Generated by setup.ps1 -- $timestamp

PROJECT_NAME=$ProjectName
REPO_URL=$RepoUrl
REPO_NAME=$RepoName
REPO_BRANCH=$RepoBranch
WORKER_COUNT=$WorkerCount
ORCHESTRATOR_PORT=3100
SMEE_CHANNEL_URL=$SmeeChannelUrl
"@
    Set-Content -Path $EnvFile -Value $envContent -NoNewline
    Write-Ok "Created $EnvFile"
}

# -- Step 6: Generate .env.local (secrets) ------------------------------------

Write-Info "Setting up credentials..."

$EnvLocalFile = Join-Path $DevcontainerDir ".env.local"
$writeLocal = $true

if (Test-Path $EnvLocalFile) {
    $overwrite = Read-Host "  ? .env.local already exists. Overwrite? [y/N]"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Warn "Keeping existing .env.local"
        $writeLocal = $false
    }
}

if ($writeLocal) {
    Write-Host ""
    Write-Info "GitHub fine-grained access token"
    Write-Host "  Create one at: https://github.com/settings/tokens?type=beta"
    Write-Host "  Required permissions: Contents (rw), Issues (rw), Pull requests (rw)"
    Write-Host ""

    $ghTokenSecure = Read-Host "  ? GitHub token" -AsSecureString
    $ghToken = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($ghTokenSecure))

    $ghUsername = Read-Host "  ? GitHub username"
    $ghEmail = Read-Host "  ? GitHub email"

    Write-Host ""
    Write-Info "Claude API key"
    Write-Host "  Get one at: https://console.anthropic.com/settings/keys"
    Write-Host ""

    $claudeKeySecure = Read-Host "  ? Claude API key" -AsSecureString
    $claudeKey = [Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [Runtime.InteropServices.Marshal]::SecureStringToBSTR($claudeKeySecure))

    $envLocalContent = @"
# Generated by setup.ps1 -- DO NOT COMMIT
GH_TOKEN=$ghToken
GH_USERNAME=$ghUsername
GH_EMAIL=$ghEmail
CLAUDE_API_KEY=$claudeKey
"@
    Set-Content -Path $EnvLocalFile -Value $envLocalContent -NoNewline
    Write-Ok "Created $EnvLocalFile"
}

# -- Step 7: Update devcontainer.json ----------------------------------------

Write-Info "Updating devcontainer.json..."

$DevcontainerJson = Join-Path $DevcontainerDir "devcontainer.json"

if (Test-Path $DevcontainerJson) {
    $content = Get-Content -Path $DevcontainerJson -Raw
    $content = $content -replace '"name": "generacy-cluster"', "`"name`": `"$ProjectName`""
    $content = $content -replace '"workspaceFolder": "/workspaces/project"', "`"workspaceFolder`": `"/workspaces/$RepoName`""
    Set-Content -Path $DevcontainerJson -Value $content -NoNewline
    Write-Ok "Updated devcontainer.json (name: $ProjectName, workspaceFolder: /workspaces/$RepoName)"
} else {
    Write-Warn "devcontainer.json not found at $DevcontainerJson"
}

# -- Step 8: Ensure ~/.claude.json exists ------------------------------------

Write-Info "Checking Claude config..."

$ClaudeJson = Join-Path $env:USERPROFILE ".claude.json"

if (-not (Test-Path $ClaudeJson)) {
    Set-Content -Path $ClaudeJson -Value "{}"
    Write-Ok "Created $ClaudeJson (required for Docker volume mount)"
} else {
    Write-Ok "$ClaudeJson already exists"
}

# -- Done ---------------------------------------------------------------------

Write-Host ""
Write-Info "Setup complete!"
Write-Host ""
Write-Host "  Next steps:"
Write-Host "    1. Open this project in VS Code"
Write-Host "    2. VS Code will prompt: 'Reopen in Container' -- click it"
Write-Host "    3. Or run manually: cd .devcontainer; docker compose up -d"
Write-Host ""
if ($SmeeChannelUrl) {
    Write-Host "  Webhook forwarding:"
    Write-Host "    Add this URL as a webhook in your GitHub repo settings:"
    Write-Host "    $SmeeChannelUrl"
    Write-Host ""
}
