"""Regression suite for the SOURCE-DEV quickstart path.

Every test here maps to a real failure found on 2026-09-01, when the quickstart
was run on a clean machine for the first time in months. None of them are
hypothetical, and none are covered by install-e2e.yml — that suite stands up the
installer's prebuilt-image artifact, so it cannot see anything that breaks in
``clone-repos.sh``, ``./jarvis init``, ``_stamp_env_files`` or ``_auto_register``.

Phase ordering mirrors what a contributor does:
    A. clone   — the repo inventory is complete and actually clones
    B. init    — succeeds on a CLEAN machine (no pre-existing docker network)
    C. start   — every service comes up
    D. wiring  — the cross-service invariants that were silently broken
    E. gpu     — the model really loaded on the GPU (source-built CUDA wheels)
"""
from __future__ import annotations

import json
import re
import subprocess

import pytest
import requests

from conftest import (
    HTTP_SERVICES,
    KNOWN_BROKEN,
    BASE_URL,
    env_values,
    http_status,
    result_lines,
    result_rc,
    result_text,
    secret_state,
)


# ── Phase A: clone ───────────────────────────────────────────────────────────
def test_clone_repos_inventory_is_complete() -> None:
    """Every service ./jarvis expects must have a clone source.

    FOUND 2026-09-01: clone-repos.sh omitted jarvis-notifications and
    jarvis-web entirely, so a fresh checkout could never start a full stack —
    ./jarvis start --all just skipped them (the loop `continue`s on a missing
    directory, so it fails silently rather than loudly).
    """
    omitted = result_lines("clone_omitted_by_script")
    assert not omitted, (
        "services in the ./jarvis SERVICES registry with no entry in "
        f"scripts/clone-repos.sh: {omitted}"
    )


def test_all_listed_repos_clone_successfully() -> None:
    """Every repo clone-repos.sh lists must actually exist and clone.

    FOUND 2026-09-01: the script lists jarvis-mcp-client, which does not exist
    on GitHub. Under the script's `set -e` that aborted the whole run at that
    point, so the ~8 repos listed after it were never cloned — and the script
    still printed its earlier progress, so it read as a partial success.
    """
    failures = result_lines("clone_failures")
    assert not failures, f"repos listed in clone-repos.sh that failed to clone: {failures}"


# ── Phase B: init ────────────────────────────────────────────────────────────
def test_init_succeeds_on_clean_machine() -> None:
    """./jarvis init must work on a box that has never run jarvis.

    FOUND 2026-09-01: `_write_network_override` — the ONLY caller of
    `docker network create jarvis-net` — runs from cmd_start, never cmd_init.
    But init's `_start_infra` brings up jarvis-data-services, whose compose
    declares jarvis-net as `external: true`. So init died with "network
    jarvis-net declared as external, but could not be found" on every clean
    machine, and could only succeed AFTER a start --all that itself needs init.
    """
    rc = result_rc("phase_init.rc")
    assert rc is not None, "init phase never ran"
    log = result_text("init.log")
    if rc != 0 and "declared as external" in log:
        pytest.fail(
            "./jarvis init failed on the jarvis-net chicken-and-egg: the network "
            "is only created by cmd_start.\n"
            + "\n".join(log.splitlines()[-15:])
        )
    assert rc == 0, "./jarvis init failed:\n" + "\n".join(log.splitlines()[-25:])


def test_init_generates_every_required_token() -> None:
    """tokens.env must carry every shared secret a service fails closed without.

    FOUND 2026-09-01: JARVIS_ADAPTER_CALLBACK_TOKEN was never generated by
    _generate_tokens nor stamped by _stamp_env_files. command-center logged
    "async-job callbacks will be REJECTED (503)" at every startup, so deep
    research, memory extraction, transcript mark_processed and inbox delivery
    all completed in the worker and then silently persisted nothing.
    """
    tokens = result_text("tokens.env")
    assert tokens, "no ~/.jarvis/tokens.env captured — init did not get that far"
    required = [
        "AUTH_SECRET_KEY",
        "JARVIS_AUTH_ADMIN_TOKEN",
        "JARVIS_CONFIG_ADMIN_TOKEN",
        "ADMIN_API_KEY",
        "MODEL_SERVICE_TOKEN",
        "JARVIS_ADAPTER_CALLBACK_TOKEN",
    ]
    missing = [k for k in required if not re.search(rf"^{k}=.+$", tokens, re.M)]
    assert not missing, f"tokens.env missing required secrets: {missing}"


# ── Phase C: start ───────────────────────────────────────────────────────────
def test_start_all_succeeds() -> None:
    rc = result_rc("phase_start.rc")
    assert rc is not None, "start phase never ran"
    assert rc == 0, "./jarvis start --all failed:\n" + "\n".join(
        result_text("start.log").splitlines()[-25:]
    )


@pytest.mark.parametrize("svc", HTTP_SERVICES, ids=lambda s: s.name)
def test_service_healthy(svc) -> None:
    if svc.name in KNOWN_BROKEN:
        pytest.xfail(KNOWN_BROKEN[svc.name])
    status = http_status(svc.port, svc.health)
    assert status == 200, f"{svc.name} :{svc.port}{svc.health} returned {status}"


def test_mqtt_broker_is_running() -> None:
    """A broker must actually exist, not merely be registered.

    FOUND 2026-09-01: ./jarvis registers jarvis-mqtt-broker at mqtt://…:1884,
    but jarvis-data-services defined no mosquitto service, so nothing ever ran
    one. Every MQTT path then failed by 10s timeout — most visibly the mobile
    app spinning forever on "Loading tools…", because GET /nodes/{id}/tools
    asks the node over MQTT.
    """
    names = result_text("docker_ps")
    assert "mosquitto" in names, (
        "no mosquitto container in the stack — MQTT-dependent features "
        "(node tool reports, MQTT TTS push) fail by timeout.\n" + names
    )


# ── Phase D: cross-service wiring ────────────────────────────────────────────
@pytest.mark.parametrize(
    "service",
    ["jarvis-command-center", "jarvis-llm-proxy-api", "jarvis-tts", "jarvis-whisper-api"],
)
def test_app_keys_are_minted(service: str) -> None:
    """App-to-app credentials must be real, not empty or placeholders.

    FOUND 2026-09-01: _auto_register reported "Registered 12 services (all
    credentials up to date)" while every JARVIS_APP_KEY was empty and
    jarvis-tts still held the literal CHANGE_ME_get_from_jarvis_auth_admin.
    Registration had actually failed (auth_ok=false) but the summary line only
    counts .env writes, so a total failure printed as success.
    """
    env = env_values(service)
    state = secret_state(env.get("JARVIS_APP_KEY"))
    assert state == "set", (
        f"{service} JARVIS_APP_KEY is {state} "
        f"({env.get('JARVIS_APP_KEY')!r}) — app-to-app auth will 401"
    )


def test_service_registration_reaches_auth() -> None:
    """config-service must be able to reach jarvis-auth to mint app keys.

    FOUND 2026-09-01: in bridge mode every service was registered at
    host:localhost + published port, and config-service's JARVIS_AUTH_URL was
    host.docker.internal:7701. A container on jarvis-net dialling a published
    port that DNATs back into jarvis-net dies on NAT hairpin, so the auth leg
    silently failed: `{"auth_ok": false, "error": "Auth service error: "}` —
    an empty error string, because the httpx exception was swallowed.
    """
    token = None
    for line in result_text("env.jarvis-config-service").splitlines():
        if line.startswith("JARVIS_AUTH_ADMIN_TOKEN="):
            token = line.partition("=")[2]
    if token is None or token.startswith("<empty"):
        pytest.skip("no admin token captured; covered by test_init_generates_every_required_token")

    # Re-registering an existing service is idempotent — we assert the auth leg,
    # not creation. The token value itself is redacted in artifacts, so read it
    # from the live stack instead.
    admin = subprocess.run(
        ["docker", "exec", "jarvis-config-service-jarvis-config-1",
         "printenv", "JARVIS_AUTH_ADMIN_TOKEN"],
        capture_output=True, text=True,
    )
    if admin.returncode != 0 or not admin.stdout.strip():
        pytest.skip("could not read admin token from the running container")

    r = requests.post(
        f"{BASE_URL}:7700/v1/services/register",
        headers={"X-Jarvis-Admin-Token": admin.stdout.strip()},
        json={"services": [{"name": "jarvis-command-center", "host": "jarvis-voice-api",
                            "port": 7703, "external_host": "localhost", "external_port": 7703}]},
        timeout=30,
    )
    assert r.status_code == 200, f"register returned {r.status_code}: {r.text[:200]}"
    result = r.json()["results"][0]
    assert result["auth_ok"] is True, (
        "config-service could not reach jarvis-auth — app keys cannot be minted. "
        f"error={result.get('error')!r}"
    )


def test_url_styles_resolve_for_each_consumer_class() -> None:
    """Each consumer class must get an address it can actually reach.

    In bridge mode host/port are CONTAINER coords and external_host/external_port
    the published ones (see jarvis-config-service/app/models.py). The three
    styles must therefore differ in the right direction — a Pi on the LAN and a
    container on jarvis-net cannot use the same URL.
    """
    def url_for(style: str, name: str = "jarvis-auth", **params) -> str | None:
        r = requests.get(f"{BASE_URL}:7700/services", params={"style": style, **params}, timeout=15)
        r.raise_for_status()
        for s in r.json()["services"]:
            if s["name"] == name:
                return s.get("url")
        return None

    default = url_for("default")
    external = url_for("external")
    remote = url_for("remote", remote_host="10.99.99.99")

    assert default, "jarvis-auth not registered"
    # In-stack callers must NOT be handed a loopback address.
    assert "localhost" not in default and "127.0.0.1" not in default, (
        f"style=default returned {default!r} — a container cannot reach that"
    )
    # Off-network clients (mobile) must get the published port, not container DNS.
    assert external and ("localhost" in external or "127.0.0.1" in external), (
        f"style=external returned {external!r} — off-docker clients need published coords"
    )
    # Another machine must get ITS reachable host, not a container name.
    assert remote and "10.99.99.99" in remote, (
        f"style=remote returned {remote!r} — remote_host rewrite did not apply, so "
        "distributed installs (a Pi node, a second host) get an unreachable URL"
    )


def test_callback_token_not_rejected_at_startup() -> None:
    """command-center must not be rejecting its own async-job callbacks."""
    logs = subprocess.run(
        ["docker", "logs", "jarvis-command-center-jarvis-voice-api-1"],
        capture_output=True, text=True,
    )
    blob = logs.stdout + logs.stderr
    assert "callbacks will be REJECTED" not in blob, (
        "JARVIS_ADAPTER_CALLBACK_TOKEN unset — every async-job callback 503s, so "
        "memory extraction, deep-research results and inbox delivery never persist"
    )


def test_migrations_are_at_head() -> None:
    """Services that ship alembic must be AT head, not merely running.

    The 2026-06 incident: config-service shipped migration 005 but never ran
    `alembic upgrade head`, so /services 500'd fleet-wide while /health stayed
    green. The source path has its own version of this — init runs migrations
    from HOST venvs, which fail differently than the container entrypoints.
    """
    log = result_text("init.log")
    if not log:
        pytest.skip("no init log captured")
    failed = re.findall(r"FAIL\s+(jarvis-[a-z-]+)", log)
    # jarvis-mcp and jarvis-recipes-server are the known host-venv failures
    # (deprecated MCP SDK; pillow-heif has no cp314 wheel) — see KNOWN_BROKEN.
    unexpected = [s for s in failed if s not in {"jarvis-mcp", "jarvis-recipes-server"}]
    assert not unexpected, f"unexpected migration failures during init: {unexpected}"


# ── Phase E: GPU proof ───────────────────────────────────────────────────────
def test_model_is_resident_on_gpu() -> None:
    """The source-built CUDA wheels must actually put the model on the GPU.

    This is why the lane rents a GPU box: jarvis-llm-proxy-api, jarvis-whisper-api
    and jarvis-tts BUILD llama.cpp / whisper.cpp wheels from source rather than
    pulling a prebuilt image, so a broken CUDA build shows up only here. A silent
    CPU fallback keeps /health green, so health alone cannot catch it.

    Measured VRAM, not log markers. install-e2e-gpu greps ggml backend-init lines
    because the installer's image emits them on stdout; the source build routes
    llama.cpp's native logs through the app logger, so those markers never appear
    even on a perfectly good CUDA build (verified locally 2026-09-01 — grepping
    would have failed a working GPU stack). This box is rented and runs nothing
    else, so multi-GB resident VRAM after a warmup inference is unambiguous.
    """
    raw = result_text("gpu_memory").strip()
    if not raw:
        pytest.skip("no nvidia-smi sample captured — run did not reach the GPU phase")

    used_mib = int(re.match(r"\s*(\d+)", raw).group(1))
    assert used_mib > 1024, (
        f"only {used_mib} MiB of VRAM in use after a warmup inference — the model "
        "is running on CPU despite a green /health. Compute apps:\n"
        + result_text("gpu_compute_apps")
    )


def test_warmup_inference_succeeded() -> None:
    """The stack must actually answer, not merely report healthy."""
    raw = result_text("warmup_inference.json").strip()
    if not raw:
        pytest.skip("no warmup inference captured (app key missing — see app-key test)")
    try:
        body = json.loads(raw)
    except json.JSONDecodeError:
        pytest.fail(f"warmup inference returned non-JSON: {raw[:200]}")
    assert "choices" in body, f"inference failed: {json.dumps(body)[:300]}"
